version: '3.8'

services:
  wahub-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_HTTP_PORT}:8080"
      - "${APP_HTTPS_PORT}:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};TrustServerCertificate=${DB_TRUST_CERT}
      - Database__AutoMigrate=${DB_AUTO_MIGRATE}
      - Database__FailOnMigrationError=${DB_FAIL_ON_ERROR}
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
    depends_on:
      - sqlserver
    networks:
      - wahub-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - wahub-network

volumes:
  sqlserver_data:

networks:
  wahub-network:
    driver: bridge
